## makeCacheMatrix and cacheSolve work together to take a matrix, calculate its inverse and keep it in memory.
## makeCacheMatrix serves to take a matrix as input and defines setter and getter functions for the matrix and its inverse.
## cacheSolve calculates the inverse of the matrix and uses makeCacheMatrix's setinverse function to cache it.





## makeCacheMatrix takes a matrix as input and creates an object that contains
## functions (set, get, setinverse, getinverse; in form of a list) and variables (i, x)

makeCacheMatrix <- function(x = matrix()) {
        i <- NULL
        set <- function(y) {
                x <<- y
                i <<- NULL
        }
        get <- function() x
        setinverse <- function(inverse) i <<- inverse
        getinverse <- function() i
        list(set = set, get = get,
             setinverse = setinverse,
             getinverse = getinverse)
}


## cacheSolve takes a makeCacheMatrix object generated by the makeCacheMatrix function as
## input and then calculates and caches the inverse of the matrix set in the makeCacheMatrix object

cacheSolve <- function(x, ...) {
    i <- x$getinverse()
    if(!is.null(i)) {
            message("getting cached data")
            return(i)
    }
    data <- x$get()
    i <- solve(data, ...)
    x$setinverse(i)
    i
}
